build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.19
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.19
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OpenAI Whisper STT"
  org.opencontainers.image.description: "OpenAI Whisper Speech-to-Text service for Home Assistant"
  org.opencontainers.image.source: "https://github.com/m0rdras/wyoming-whisper-openai"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0" 
