name: "OpenAI Whisper STT"
version: "1.0.0"
slug: "wyoming-whisper-openai"
description: "OpenAI Whisper Speech-to-Text service for Home Assistant"
url: "https://github.com/m0rdras/wyoming-whisper-openai-client"
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
ports:
  "7891/tcp": 7891
ports_description:
  7891/tcp: "Wyoming Protocol port"
options:
  openai_api_key: ""
  language: "en"
schema:
  openai_api_key: password
  language: list(af|am|ar|as|az|ba|be|bg|bn|bo|br|bs|ca|cs|cy|da|de|el|en|es|et|eu|fa|fi|fo|fr|gl|gu|ha|haw|he|hi|hr|ht|hu|hy|id|is|it|ja|jw|ka|kk|km|kn|ko|la|lb|ln|lo|lt|lv|mg|mi|mk|ml|mn|mr|ms|mt|my|ne|nl|nn|no|oc|pa|pl|ps|pt|ro|ru|sa|sd|si|sk|sl|sn|so|sq|sr|su|sv|sw|ta|te|tg|th|tk|tl|tr|tt|uk|ur|uz|vi|yi|yo|zh)?
image: "ghcr.io/m0rdras/wyoming-whisper-openai-addon"