name: Builder

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Add-on
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --aarch64 \
            --target addon \
            --docker-hub ghcr.io/m0rdras \
            --image wyoming-whisper-openai-addon \
            --version 1.0.0